user-command-service:
  build: ./user-command-service/
  ports:
  - 7081:8080

user-query-service:
  build: ./user-query-service/
  ports:
  - 7082:8080

#############################################################

cart-command-service:
  build: ./cart-command-service/
  ports:
  - 7083:8080

cart-query-service:
  build: ./cart-query-service/
  ports:
  - 7084:8080

#############################################################

product-query-service:
  build: ./product-query-service/
  ports:
  - 7085:8080

#############################################################

store-command-service-1:
  build: ./store-command-service/
  ports:
  - 7086:8080

# store-command-service-2:
#   build: ./store-command-service/
#   ports:
#   - 7087:8080

#############################################################

gateway-service:
  build: ./gateway-service/
  ports:
  - 7088:8080
